# Binary sensors

# Camera motion sensors
# - platform: template
#   sensors:
#     altancam_motion:
#       friendly_name: Altancam motion
#       device_class: motion
#       entity_id: camera.altan
#       value_template: "{{ is_state('camera.altan', 'motion') }}"
#       delay_off:
#         seconds: 30
#     garagecam_motion:
#       friendly_name: Garagecam motion
#       device_class: motion
#       entity_id: camera.garage
#       value_template: "{{ is_state('camera.garage', 'motion') }}"
#       delay_off:
#         seconds: 30
- platform: template
  sensors:
    people_home:
      friendly_name: 'People Home'
      device_class: presence
      value_template: >
        {{ is_state('person.armin', 'home') or
            is_state('person.mali', 'home') }}

# RFXtrx433XL sensors, needs host restart for automatic_add change
# - platform: rfxtrx
#   automatic_add: false
#   devices:
#     0b11004a02ae03fa10010f60:
#       name: main_door

- platform: template
  sensors:
    frontdoor:
      friendly_name: "Frontdoor"
      #device_class: door # does not work since copy from bin sens.
      value_template: >-
        {% if is_state("binary_sensor.main_door", "on") %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.main_door", "on") %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
